version: 2
updates:
  - package-ecosystem: "github-action"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "gomod"
    directory: "/assets"
    schedule:
      interval: monthly
